### ISSUE TITLE
unnamed enum issue on macos

### ISSUE THREAD

**Issue by kcking** [coupler-rs/vst3-bindgen#1]
When using vst3-bindgen in a blank project, i get the following compilation error:
```rust
error: expected identifier, found `(`
  --> /Users/.../target/debug/build/vst3-bindgen-2dd1585f0690fcd4/out/bindings.rs:25:14
   |
25 |     pub type (unnamed enum at /Users/.../vst3sdk/pluginterfaces/base/funknown.h:189:1) = ::std::ffi::c_int;
   |              ^ expected identifier
```
It appears the unnamed enum is actually named `(unnamed enum at /Users/.../vst3sdk/pluginterfaces/base/funknown.h:189:1)` instead of being the empty string.

llvm `16.0.4` (installed with brew)
vst3sdk `v3.7.7_build_19`
macOS

**Comment by glowcoil** [comment]
It turns out this is happening because vst3-bindgen detects unnamed/anonymous declarations by checking if the name was an empty string, but libclang's behavior was changed in version 16 to start returning names like `(unnamed enum at ...)` instead. Bindgen had to fix the same issue a few months ago: https://github.com/rust-lang/rust-bindgen/pull/2319
